sudo: required
services:
  - docker

before_install:
  - docker build -t mgaygisiz/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true mgaygisiz/frontend npm run test

after_success:
# Build Prod Containers
  - docker build -t mgaygisiz/frontend .
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push built images to Docker Hub
  - docker push mgaygisiz/frontend

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "frontend"
#  env: "Frontend-env"
#  bucket_name: "elasticbeanstalk-us-east-2-178022083866"
#  bucket_path: "frontend"
#  on:
#    branch: master
#  access_key_id:
#    secure: "$AWS_ACCESS_KEY"
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"